#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tasky.Droid.Resource", IsApplication=true)]

namespace Tasky.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int ic_action_addtask = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ic_action_delete = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_action_save = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_checkmark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher = 2130771972;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int checkMark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int checkmark = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int chkDone = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int lblDescription = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int lblName = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int linearLayout1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int lstTasks = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int menu_add_task = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int menu_delete_task = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int menu_save_task = 2130837515;
			
			// aapt resource value: 0x7F020000
			public const int NameLabel = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int NotesLabel = 2130837505;
			
			// aapt resource value: 0x7F02000C
			public const int txtName = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int txtNotes = 2130837517;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int TaskDetails = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int TaskListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int menu_detailsscreen = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int menu_homescreen = 2130968577;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int Theme_TaskyPro = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
